spring:
  data:
    mongodb:
      uri: mongodb://admin:spirit@dyvakdb-shard-00-00-ykmjr.mongodb.net:27017,dyvakdb-shard-00-01-ykmjr.mongodb.net:27017,dyvakdb-shard-00-02-ykmjr.mongodb.net:27017/test?ssl=true&replicaSet=DyvakDB-shard-0&authSource=admin&retryWrites=true
server:
  port: 8000
  email: dyvakyurii@gmail.com

